server {
    listen 80;
    server_name _;

    location /canal.m3u8 {
        proxy_pass http://138.186.23.7:8082/CINECANAL/tracks-v1a1/mono.ts.m3u8;
        proxy_set_header Host 138.186.23.7;
    }
}